
# Ch05. pandas 시작하기

In [154]:
from pandas import Series, DataFrame

In [155]:
import pandas as pd

##5.1 pandas 자료 구조 소개

###5.1.1 Series

In [156]:
#Series는 일련의 객체를 담을 수 있는 1차원 배열같은 자료구조
obj = Series([4,7,-5,3])

In [157]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [158]:
type(obj)

pandas.core.series.Series

In [159]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [160]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [161]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])
#value 와 index 지정가능

In [162]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [163]:
obj2['a']

-5

In [164]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [165]:
obj2['a']

-5

In [166]:
obj2['d'] = 6

In [167]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [168]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [169]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [170]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [171]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [172]:
import numpy as np

In [173]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [174]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [175]:
'b' in obj2
#obj2에 'b' 색인이 있는지 확인

True

In [176]:
'e' in obj2

False

In [177]:
12 in obj2

False

In [178]:
6 in obj2

False

In [179]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [180]:
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [181]:
type(sdata)

dict

In [182]:
obj3=Series(sdata)

In [183]:
obj3
#Series에 dict를 인자로 넣으면 [index : value] 형태로 저장이됨

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [184]:
obj3['Ohio'],obj3[0]

(35000, 35000)

In [185]:
states= ['California','Ohio','Oregon','Texas']

In [186]:
obj4=Series(sdata,index=states)
#'California'는 index가 없으므로 values가 Nan

In [187]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [188]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [189]:
obj.index = ['Bob','Steve','Jeff','Ryan']
#색인의 이름을 변경

In [190]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

###5.1.2 DataFrame

In [191]:
data = {'state' : ['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year' : [2000,2001,2002,2001,2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}

In [192]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [193]:
frame= DataFrame(data)
#DataFrame은 표 같은 스프레드시트 형식의 자료 구조로 여러 개의
#colum이 있는데, 각 colum은 서로 다른 종류의 값
#(숫자,문자열,boolean)을 담을수 있다.

In [194]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [195]:
type(frame)

pandas.core.frame.DataFrame

In [212]:
DataFrame(data,columns=['year','state','pop'])
#원하는 순서대로 columns를 지정이 가능

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [209]:
DataFrame(data,index=['A','B',3,4,'Five'])
#columns와 달리 자신이 원하는 index를 지정이 가능하다

pop   state  year
A     1.5    Ohio  2000
B     1.7    Ohio  2001
3     3.6    Ohio  2002
4     2.4  Nevada  2001
Five  2.9  Nevada  2002

In [213]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],
                   index=['one','two','three','four','five'])
#존재하지않는 column_key 값을 지정시, NaN(Not a Number)가 됨
#index는 자신이 지정한 형태로 각 index가 바뀜

In [214]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [215]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [227]:
print frame2['state']
print
print frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object


In [228]:
print frame2['year']
print
print frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64


In [231]:
frame2.ix['three']
#ix(=index의 줄임말로 생각하여) 해당 index의 정보를 반환

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [232]:
frame2['debt'] = 16.5

In [233]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [266]:
frame2['debt'] = np.arange(5)
#Numpy.arange(start,end,interval)

In [267]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [268]:
val = Series([-1.2, -1.5, -1.7],index=['two','four','five'])

In [269]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [274]:
frame2['debt']=val
#index가 같은 column에 value를 대입

In [275]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [280]:
frame2['eastern'] = frame2.state == 'Ohio'
#frame2.state == 'Ohio' 논리연산후 T/F를 column[eastern]에 대입

In [278]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [283]:
del frame2['eastern']

In [284]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [285]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [298]:
pop = {'Nevada': {2001: 2.4,2002: 2.9},'Ohio':{2000:1.5, 2001: 1.7, 2002: 3.6}}

In [299]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [300]:
type(pop)

dict

In [301]:
type(pop['Nevada'][2001])

float

In [302]:
pop['Nevada'][2001]

2.4

In [297]:
frame3 = DataFrame(pop)

In [303]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [313]:
frame3.T
#행과 열을 transform

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [314]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [332]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}

In [351]:
pdata

{'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [352]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [358]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
#index의 이름은 'year',column의 이름은 'state'

In [359]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [360]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [362]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [442]:
frame2.values

array([[2000L, 'Ohio', 1.5, nan],
       [2001L, 'Ohio', 1.7, -1.2],
       [2002L, 'Ohio', 3.6, nan],
       [2001L, 'Nevada', 2.4, -1.5],
       [2002L, 'Nevada', 2.9, -1.7]], dtype=object)

###5.1.3 색인 객체

In [471]:
obj = Series(range(3),index=['a','b','c'])

In [472]:
obj

a    0
b    1
c    2
dtype: int64

In [473]:
index = obj.index

In [474]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [475]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [476]:
index[1] = 'd'

TypeError: Indexes does not support mutable operations

In [477]:
type(index[0])

str