
# Ch05. pandas 시작하기

In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

## 5.1 pandas 자료 구조 소개

### 5.1.1 Series

In [3]:
#Series는 일련의 객체를 담을 수 있는 1차원 배열같은 자료구조
obj = Series([4,7,-5,3])
#보통 Series는 Series([values],index=[index]) 이러한 형태로 만듦

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
type(obj)

pandas.core.series.Series

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [8]:
obj2=Series([4,7,-5,3],index=['d','b','a','c'])
#value 와 index 지정가능

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2['a']

-5

In [11]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [15]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [16]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
import numpy as np

In [20]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [21]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [22]:
'b' in obj2
#obj2에 'b' 색인이 있는지 확인

True

In [23]:
'e' in obj2

False

In [24]:
12 in obj2

False

In [25]:
6 in obj2

False

In [26]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [27]:
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [28]:
type(sdata)

dict

In [29]:
obj3=Series(sdata)

In [30]:
obj3
#Series에 dict를 인자로 넣으면 [index : value] 형태로 저장이 됨

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [31]:
obj3['Ohio'],obj3[0]

(35000, 35000)

In [32]:
states= ['California','Ohio','Oregon','Texas']

In [33]:
obj4=Series(sdata,index=states)
#'California'는 index가 없으므로 values가 Nan

In [34]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ['Bob','Steve','Jeff','Ryan']
#색인의 이름을 변경

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [38]:
data = {'state' : ['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year' : [2000,2001,2002,2001,2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}

In [39]:
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [40]:
frame= DataFrame(data)
#DataFrame은 표 같은 스프레드시트 형식의 자료 구조로 여러 개의
#colum이 있는데, 각 colum은 서로 다른 종류의 값
#(숫자,문자열,boolean)을 담을수 있다.

In [41]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [42]:
type(frame)

pandas.core.frame.DataFrame

In [43]:
DataFrame(data,columns=['year','state','pop'])
#원하는 순서대로 columns를 지정이 가능

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [44]:
DataFrame(data,index=['A','B',3,4,'Five'])
#columns와 달리 자신이 원하는 index를 지정이 가능하다

pop   state  year
A     1.5    Ohio  2000
B     1.7    Ohio  2001
3     3.6    Ohio  2002
4     2.4  Nevada  2001
Five  2.9  Nevada  2002

In [45]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],
                   index=['one','two','three','four','five'])
#존재하지않는 column_key 값을 지정시, NaN(Not a Number)가 됨
#index는 자신이 지정한 형태로 각 index가 바뀜

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [47]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [48]:
print frame2['state']
print
print frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object


In [49]:
print frame2['year']
print
print frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64


In [50]:
frame2.ix['three']
#ix(=index의 줄임말로 생각하여) 해당 index의 정보를 반환

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2['debt'] = 16.5

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [53]:
frame2['debt'] = np.arange(5)
#Numpy.arange(start,end,interval)

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [55]:
val = Series([-1.2, -1.5, -1.7],index=['two','four','five'])

In [56]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [57]:
frame2['debt']=val
#index가 같은 column에 value를 대입

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [59]:
frame2['eastern'] = frame2.state == 'Ohio'
#frame2.state == 'Ohio' 논리연산후 T/F를 column[eastern]에 대입

In [60]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [61]:
del frame2['eastern']

In [62]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [64]:
pop = {'Nevada': {2001: 2.4,2002: 2.9},'Ohio':{2000:1.5, 2001: 1.7, 2002: 3.6}}

In [65]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [66]:
type(pop)

dict

In [67]:
type(pop['Nevada'][2001])

float

In [68]:
pop['Nevada'][2001]

2.4

In [69]:
frame3 = DataFrame(pop)

In [70]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [71]:
frame3.T
#행과 열을 transform

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [72]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [73]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}

In [74]:
pdata

{'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [75]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [76]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
#index의 이름은 'year',column의 이름은 'state'

In [77]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [78]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [80]:
frame2.values

array([[2000L, 'Ohio', 1.5, nan],
       [2001L, 'Ohio', 1.7, -1.2],
       [2002L, 'Ohio', 3.6, nan],
       [2001L, 'Nevada', 2.4, -1.5],
       [2002L, 'Nevada', 2.9, -1.7]], dtype=object)

### 5.1.3 색인 객체

In [81]:
obj = Series(range(3),index=['a','b','c'])

In [82]:
obj

a    0
b    1
c    2
dtype: int64

In [83]:
index = obj.index

In [84]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [85]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [86]:
index[1]

'b'

In [87]:
index[1] = 'd'
#색인은 변경이 불가능함

TypeError: Indexes does not support mutable operations

In [102]:
index = pd.Index(np.arange(3))

In [103]:
index

Int64Index([0, 1, 2], dtype='int64')

In [104]:
obj2 = Series([-1.5, -2.5, 0], index = index)

In [105]:
obj2

0   -1.5
1   -2.5
2    0.0
dtype: float64

In [106]:
obj2.index is index

True

In [107]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [108]:
'Ohio' in frame3
#column에 대해서 'Ohio' 존재?

True

In [109]:
2000 in frame3
#column에 대해서 2000 존재?

False

In [110]:
#그러면 index에 대해선 어떻게 확인?
2000 in frame3.index

True

In [111]:
2003 in frame3.index

False

## 5.2 핵심 기능

### 5.2.1 재색인

In [112]:
obj = Series([4.5, 7.2, -5.3, 3.6],index=['d','b','a','c'])

In [113]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [114]:
obj2 = obj.reindex(['a','b','c','d','e'])
#색인을 다시 설정

In [115]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [116]:
obj.reindex(['a','b','c','d','e'],fill_value=0)
#비어있는곳은 0으로 채우기

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [117]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [118]:
obj3
#현재 index가 0,2,4 만 있고 1,3은 없는 상태

0      blue
2    purple
4    yellow
dtype: object

In [119]:
obj3.reindex(range(6),method="ffill")
#5까지의 index들중 누락된 index들을 채워줌(value는 앞의 값과 동일(=ffill(front_fill)))
#---------- reindex 메서드(보간) 옵션 ----------
#1. ffill 또는 pad : 앞의 값으로 채워 넣는다.
#2. bfill 또는 backfill : 뒤의 값으로 채워 넣는다.

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [120]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [121]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [122]:
obj3.reindex(range(6),method="bfill")
#value는 뒤의 값과 동일(=bfill(back_fill))

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [123]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [124]:
frame = DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [125]:
frame.shape

(3, 3)

In [126]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [127]:
frame2 = frame.reindex(['a','b','c','d'])

In [128]:
frame2

Ohio  Texas  California
a     0      1           2
b   NaN    NaN         NaN
c     3      4           5
d     6      7           8

In [129]:
states = ['Texas', 'Utah', 'California']

In [130]:
frame.reindex(columns=states)
#column을 변수로 대입가능

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [132]:
frame.reindex(index=['a','b','c','d'],method='ffill',columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [133]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a      1   NaN           2
b    NaN   NaN         NaN
c      4   NaN           5
d      7   NaN           8

###5.2.2 하나의 로우 또는 칼럼 삭제하기

In [134]:
#drop 메서드를 사용하면 선택한 값이 삭제된 새로운 객체를 얻을수 있다.
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [135]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: float64

In [136]:
new_obj = obj.drop('c')
#column = 'c'부분을 drop

In [137]:
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [138]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: float64

In [139]:
data = DataFrame(np.arange(16).reshape(4,4),index = ['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [140]:
data.drop(['Colorado','Utah'])

one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [141]:
data.drop('two',axis=1)
#1번축의 'two' 제거

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [142]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [143]:
data.drop(['Ohio','Utah'],axis=0)
#0번축의 'Ohio','Utah'제거(default=0)

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

###5.2.3 색인하기, 선택하기, 거르기

In [144]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [145]:
obj

a    0
b    1
c    2
d    3
dtype: float64

In [146]:
print obj['b']
print
print obj[1]

1.0

1.0


In [147]:
print obj[2:4]
print
print obj[['b','a','d']]

c    2
d    3
dtype: float64

b    1
a    0
d    3
dtype: float64


In [148]:
obj[['b','a']]
#안에 리스트형태가 들어가야함

b    1
a    0
dtype: float64

In [149]:
obj[[1,3]]

b    1
d    3
dtype: float64

In [150]:
obj[obj<2]

a    0
b    1
dtype: float64

In [151]:
obj['b':'c']
#라벨이름으로 슬라이싱할 경우 시작점과 끝점을 포함하는 점이 다르다!

b    1
c    2
dtype: float64

In [152]:
obj['b':'c']=5

In [153]:
obj

a    0
b    5
c    5
d    3
dtype: float64

In [154]:
data = DataFrame(np.arange(16).reshape(4,4),
                index=['Ohio','Colorado','Utah','New York'],
                columns=['one','two','three','four'])

In [155]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [156]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [157]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [158]:
data[:2]
#index를 1까지

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [159]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [160]:
data[data['three']>5]
#data['Colorado','Utah','New York']

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data <5
#모든요소를 각각 검사
#????

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [162]:
data[data<5] = 0

In [163]:
data
#이전에서 True처리된 요소들 전부 0으로 밝혀짐

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [164]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [165]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [166]:
data.ix[2]
#index[2]인 Utah의 정보

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [167]:
data.ix[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [168]:
data.ix[data.three>5,:3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

##5.2.4 산술연산과 데이터 정렬

In [169]:
s1 = Series([7.3, -2.5, 3.4, 1.5],index=['a','c','d','e'])

In [170]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a','c','e','f','g'])

In [171]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [172]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [173]:
s1 + s2
#객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [174]:
df1 = DataFrame(np.arange(9.).reshape((3,3)),columns=(list('bcd')),index=['Ohio','Texas','Colorado'])
#columns = (['b','c','d']) 와 list('bcd') 는 동일
#0~8을 3*3형태로 columns은 'b','c','d'로 index 는 'Ohio','Texax','Colorado'

In [175]:
df2 = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [176]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [177]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [178]:
df1 + df2
#columns 와 index 가 하나로 합쳐짐(이때 존재하지않는 값은 NaN(Not a Number))

b   c   d   e
Colorado NaN NaN NaN NaN
Ohio       3 NaN   6 NaN
Oregon   NaN NaN NaN NaN
Texas      9 NaN  12 NaN
Utah     NaN NaN NaN NaN

In [179]:
#산술연산 메서드에 채워 넣을값 지정하기
df1 = DataFrame(np.arange(12.).reshape(3,4),columns=list('abcd'))
#columns = ['a','b','c','d']와 같음

In [180]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [181]:
df2 = DataFrame(np.arange(20.).reshape(4,5),columns=list('abcde'))

In [182]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [183]:
df1 + df2
#겹치지 않으면 무조건 NaN

a   b   c   d   e
0   0   2   4   6 NaN
1   9  11  13  15 NaN
2  18  20  22  24 NaN
3 NaN NaN NaN NaN NaN

In [184]:
df1.add(df2,fill_value=0)
#df1 + df2 와 같음, NaN은 0으로

a   b   c   d   e
0   0   2   4   6   4
1   9  11  13  15   9
2  18  20  22  24  14
3  15  16  17  18  19

In [185]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [186]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [187]:
df1.reindex(columns=df2.columns,fill_value=0) 
#df1에서 df2에 존재하는 columns를 탐색,NaN=0

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [188]:
#DataFrame 과 Series 간의 연산
arr = np.arange(12.).reshape(3,4)

In [189]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [190]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [191]:
arr[1]

array([ 4.,  5.,  6.,  7.])

In [192]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [193]:
frame = DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [194]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [195]:
series = frame.ix[0]

In [196]:
series

b    0
d    1
e    2
Name: Utah, dtype: float64

In [197]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [198]:
series2 = Series(range(3),index=['b','e','f'])

In [199]:
series2

b    0
e    1
f    2
dtype: int64

In [200]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [201]:
frame + series2
#겹치는 부분이 없으면 NaN

b   d   e   f
Utah    0 NaN   3 NaN
Ohio    3 NaN   6 NaN
Texas   6 NaN   9 NaN
Oregon  9 NaN  12 NaN

In [202]:
series3 = frame['d']

In [203]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [204]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: float64

In [205]:
frame.sub(series3,axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

###5.2.5 함수 적용과 매핑

In [206]:
frame = DataFrame(np.random.randn(4,3),columns=list('bce'),index=['Utah','Ohio','Texas','Oregon'])

In [207]:
frame

b         c         e
Utah    0.025429 -0.517290  0.738289
Ohio    0.612666  0.655220  0.482705
Texas  -0.562656 -0.588579  0.519122
Oregon  0.091595  0.165583 -1.150173

In [208]:
np.abs(frame)

b         c         e
Utah    0.025429  0.517290  0.738289
Ohio    0.612666  0.655220  0.482705
Texas   0.562656  0.588579  0.519122
Oregon  0.091595  0.165583  1.150173

In [209]:
f = lambda x: x.max() - x.min()
#파이썬은 익명 함수 혹은 lambda 함수라고 하는, 값을 반환하는 단순한 문장으로 이루진 함수를 지원

In [210]:
frame.apply(f)
#axis=0 -> 각 index에 대해서 적용

b    1.175322
c    1.243799
e    1.888462
dtype: float64

In [211]:
frame.apply(f,axis=1)

Utah      1.255579
Ohio      0.172515
Texas     1.107701
Oregon    1.315757
dtype: float64

In [212]:
def f(x):
    return Series([x.min(), x.max()], index=['min','max'])
#함수 f는 인자로 받은 x의 max와 min을 Series의 원소로하여 반환하는 함수

In [213]:
frame.apply(f)

b         c         e
min -0.562656 -0.588579 -1.150173
max  0.612666  0.655220  0.738289

In [214]:
format = lambda x: '%.2f' % x
# '%.2f' % x 에서 '%' ??????????

In [215]:
frame

b         c         e
Utah    0.025429 -0.517290  0.738289
Ohio    0.612666  0.655220  0.482705
Texas  -0.562656 -0.588579  0.519122
Oregon  0.091595  0.165583 -1.150173

In [216]:
frame.applymap(format)

b      c      e
Utah     0.03  -0.52   0.74
Ohio     0.61   0.66   0.48
Texas   -0.56  -0.59   0.52
Oregon   0.09   0.17  -1.15

In [217]:
frame['e'].map(format)

Utah       0.74
Ohio       0.48
Texas      0.52
Oregon    -1.15
Name: e, dtype: object

###5.2.6 정렬과 순위

In [218]:
obj = Series(range(4),index=['b','a','b','c'])

In [219]:
obj.sort_index()
#index를 기준으로 sorting

a    1
b    2
b    0
c    3
dtype: int64

In [220]:
frame = DataFrame(np.arange(8).reshape(2,4),index=['three','one'],columns=['d','a','b','c'])

In [221]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [222]:
frame.sort_index(axis=1)
#axis=1 -> columns를 기준으로 sorting

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [223]:
frame.sort_index(axis=1,ascending=False)
#내림차순으로 정렬

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [224]:
obj = Series([4, 7, -3, 2])

In [225]:
obj.order()

2   -3
3    2
0    4
1    7
dtype: int64

In [226]:
obj = Series([4, np.nan, 7, -3,2])

In [227]:
obj.order()
#비어있는 값은 Series 객체에서 가장 마지막에 위치

3    -3
4     2
0     4
2     7
1   NaN
dtype: float64

In [228]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [229]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [230]:
frame.sort_index(by='b')
#'b'의 기준에 따른 sorting

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [231]:
frame.sort_index(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [232]:
obj = Series([7,-5,7,4,2,0,4])

In [233]:
obj.rank()
#동률인 순위는 평균 순의를 매김

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [234]:
obj.rank(method='first')
#데이터상에서 나타는 순서에 따라 순위를 매길 수도 있음

0    6
1    1
2    7
3    4
4    3
5    2
6    5
dtype: float64

In [235]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [236]:
obj.rank(ascending=False,method='max')
#내림차순으로, 같은 값을 가질경우 숫자가 더 큰 수의 순위로 매김(더 높은순위가 아님)

0    2
1    7
2    2
3    4
4    5
5    6
6    4
dtype: float64

In [237]:
obj.rank(ascending=False,method='min')
#내림차순으로, 같은 값을 가질경우 숫자가 더 작은 수의 순위로 매김(더 높은순위로 매김)

0    1
1    7
2    1
3    3
4    5
5    6
6    3
dtype: float64

In [238]:
obj.rank(ascending=False,method='first')
#내림차순으로, 같은 값을 가질경우 순차적으로 순위를 매김

0    1
1    7
2    2
3    3
4    5
5    6
6    4
dtype: float64

In [239]:
obj.rank(ascending=False,method='average')
#내림차순으로, 각 항목에 대하여 순위릐 평균을 매김

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [240]:
frame = DataFrame({'b':[4.3, 7,-3,2],
                   'a':[0,1,0,1],
                  'c':[-2,5,8,-2.5]})

In [241]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [242]:
frame.rank(axis=1)
#axis = 1 -> column을 비교하여 rank를 매겨서 정함

a  b  c
0  2  3  1
1  1  3  2
2  2  1  3
3  2  3  1

###5.2.7 중복 색인

In [243]:
#지금까지 살펴본 예제는 모두 축의 이름(색인 값)이 유일했음. 이제 색인 값이 중복된 Series 객체를 살펴보자
obj = Series(range(5),index=['a','a','b','b','c'])

In [244]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [245]:
obj.index.is_unique
#is_unique 속성은 해당 값이 유일한지 아닌지 알려줌

False

In [246]:
obj['a']
#중복되는 색인 값이 있으면 Series 객체 반환

a    0
a    1
dtype: int64

In [247]:
obj['c']
#중복되는 색인 값이 없으면 스칼라 값 반환

4

In [248]:
df = DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [249]:
df

0         1         2
a -0.835253  0.020704 -1.051444
a  1.600844 -0.991649 -0.217705
b  0.029249  0.138578 -0.673237
b  2.282498 -0.138561  1.158734

In [250]:
df.ix['b']

0         1         2
b  0.029249  0.138578 -0.673237
b  2.282498 -0.138561  1.158734

##5.3 기술통계 계산과 요약

In [251]:
#pandas의 메서드는 처음부터 누락된 데이터를 제외하도록 설계되었다.
df = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [252]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [253]:
df.sum()
#각 column에 대한 sum 연산결과

one    9.25
two   -5.80
dtype: float64

In [254]:
df.sum(axis=1)
#각 row에 대한 sum 연산결과

a    1.40
b    2.60
c     NaN
d   -0.55
dtype: float64

In [255]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [256]:
#전체 로우나 칼럼의 값이 NaN이 아니라면 계산과정에서 NaN값은 제외시키고 계산된다.
#이는 skipna옵션을 통해 조정할 수 있다.
df.mean(axis=1,skipna=False)
#mean은 평균을 구하는 메서드
#skipna -> NaN은 제외합니까? T(제외)/F(포함)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [257]:
df.idxmax()
#max값을 가지는 index 반환

one    b
two    d
dtype: object

In [258]:
df.cumsum()
#cumsum() -> 누적합을 구함(NaN은 제외)

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [259]:
df.describe()
#describe() -> 한번에 여러가지 통계결과는 만들어내는 메서드

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [260]:
obj = Series(['a','a','b','c']*4)
#Series['a','a','b','c']를 4번 반복

In [261]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [262]:
obj.describe()
#count -> index의 수
#unique -> 중복제거된 값의 수
#top -> 첫번째 색인의 값
#freq -> 가장 빈번하게 나타난 값의 빈도

count     16
unique     3
top        a
freq       8
dtype: object

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

###5.3.1 상관관계와 공분산

In [263]:
import pandas.io.data as web

In [264]:
all_data={}
for ticker in ['AAPL','IMB','MSFT','GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')
    
price = DataFrame({tic : data['Adj Close'] for tic, data in all_data.iteritems()})
volume = DataFrame({tic : data['Volume'] for tic, data in all_data.iteritems()})

IOError: after 3 tries, Yahoo! did not return a 200 for url 'http://ichart.finance.yahoo.com/table.csv?s=IMB&a=0&b=1&c=2000&d=0&e=1&f=2010&g=d&ignore=.csv'

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

###5.3.2 유일 값, 값 세기, 멤버십

In [266]:
obj = Series(['c','a','d','a','a','b','b','c','c'])

In [267]:
uniques = obj.unique()

In [268]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [269]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [270]:
pd.value_counts(obj.values,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [271]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [272]:
mask = obj.isin(['b','c'])

In [273]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [274]:
obj[mask]
#True인것만 추출하여 출력

0    c
5    b
6    b
7    c
8    c
dtype: object

In [275]:
data = DataFrame({'Qu1':[1,3,4,3,4],
                 'Qu2':[2,3,1,2,3],
                 'Qu3':[1,5,2,4,4]})

In [276]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [277]:
result = data.apply(pd.value_counts).fillna(0)

In [279]:
result

Qu1  Qu2  Qu3
1    1    1    1
2    0    2    1
3    2    2    0
4    2    0    2
5    0    0    1

##5.4 누락된 데이터 처리하기

In [283]:
#pandas 객체의 모든 기술통계는 누락된 데이터를 배제하고 처리
#pandas는 ㅜ락된 데이터를 모두 NanN(Not a Number)로 취급
string_data = Series(['aardvark','artichoke',np.nan,'avocado'])
#np.nan -> NaN

In [282]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [285]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [286]:
string_data[0] = None

In [288]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

###5.4.1 누락된 데이터 골라내기

In [290]:
#Series에 대해 dropna 메서드를 적용하면 실제 데이터가 들어있는 색인 값과 데이터를 Series 값으로 반환한다.
from numpy import nan as NA

In [291]:
data = Series([1,NA,3.5,NA,7])

In [293]:
data.dropna()
#NaN은 제외하고 반환

0    1.0
2    3.5
4    7.0
dtype: float64

In [295]:
data[data.notnull()]
#불리언 색인을 이용하여 직접계산도 가능

0    1.0
2    3.5
4    7.0
dtype: float64

In [296]:
data = DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [299]:
data

0    1   2
0   1  6.5   3
1   1  NaN NaN
2 NaN  NaN NaN
3 NaN  6.5   3

In [297]:
cleanded = data.dropna()

In [298]:
cleanded

0    1  2
0  1  6.5  3

In [301]:
data.dropna(how='all')
#how='all' 옵션을 주면 모든 column이 NaN인 로우만 제외

0    1   2
0   1  6.5   3
1   1  NaN NaN
3 NaN  6.5   3

In [302]:
data[4] = NA

In [303]:
data

0    1   2   4
0   1  6.5   3 NaN
1   1  NaN NaN NaN
2 NaN  NaN NaN NaN
3 NaN  6.5   3 NaN

In [304]:
data.dropna(axis=1,how='all')

0    1   2
0   1  6.5   3
1   1  NaN NaN
2 NaN  NaN NaN
3 NaN  6.5   3

In [305]:
df = DataFrame(np.random.randn(7,3))

In [306]:
df.ix[:4,1] = NA
df.ix[:2,2] = NA

In [307]:
df

0         1         2
0  2.444895       NaN       NaN
1  0.768922       NaN       NaN
2 -1.315686       NaN       NaN
3  1.228047       NaN  0.094483
4  0.326613       NaN  0.176034
5  0.282806 -0.970212 -1.508875
6 -1.199227  0.787021  0.087529